ruby "2.4.0"
source "https://rubygems.org"
gem "bundler", "1.16.2"
gem "sinatra"
gem "sinatra-contrib"
gem "mecab", "0.996"
gem "pry"
gem "sinatra-asset-pipeline"
gem "sass"
gem "sinatra-formhelpers-ng"
